load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "filegroup",
    srcs = ["lang.go"],
    importpath = "github.com/EngFlow/gazelle_cc/language/filegroup",
    visibility = ["//visibility:public"],
    deps = [
        "@gazelle//config",
        "@gazelle//label",
        "@gazelle//language",
        "@gazelle//repo",
        "@gazelle//resolve",
        "@gazelle//rule",
    ],
)
